apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: mynode
          image: gcr.io/sit737-23t1-thakoor-f585186/my-hello-world-app:tag2
          ports:
            - containerPort: 3000
